### ISSUE TITLE
.so loading ModuleLoader

### ISSUE THREAD

**Issue by gmorenz** [murarth/ketos#10]
I've created a (mostly untested) `ModuleLoader` that loads .so file, and imports functions that don't start with '_' as system functions. The relevant code is in `src/dyn_loader.rs`.

This is unsafe and easy to cause segfaults with so I would recommend against bringing it in tree, but I thought you might like to know about it ;)

[link](https://gitlab.com/gmorenz/rust-ketos-repl/tree/master)

**Comment by murarth** [comment]
Loading all symbols is definitely an *interesting* way of doing this. Some other method that's a bit saner and safer would be preferred and may be implemented eventually. I'm not sure about the logistics of building Rust programs that load plugin libraries.

**Comment by gmorenz** [comment]
Saner and safer would certainly be nice. I don't think it's possible at present, but hopefully the ecosystem (and compiler) will develop in this area. There has been pretty much no work on type safe plugin loading in rust that I'm aware of.
