### ISSUE TITLE
Define structure in module

### ISSUE THREAD

**Issue by hauleth** [murarth/ketos#14]
How to define structure in Rust module?

**Comment by murarth** [comment]
Do you mean a structure definition or a value? Or both?

**Comment by hauleth** [comment]
I am more interested in structure definition, but instructions for both would be nice. 

--
Łukasz Jan Niemier

Dnia 27 lut 2016 o godz. 00:18 Murarth <notifications@github.com> napisał(a):

**Comment by murarth** [comment]
A builder pattern struct could do the job, but I'm not sure if that's any more convenient than running Ketos code to define it. Would you have any objection to using something like `execute(scope, "(struct Foo ...)")`?
