### ISSUE TITLE
Allow closures in FunctionImpl

### ISSUE THREAD

**Issue by vktec** [murarth/ketos#23]
Allowing closures in FunctionImpl would allow one to call methods from Ketos, thus allowing a state to be shared between calls. This would (in my opinion) make Ketos much more appealing for embedding into other programs, as Ketos code could manipulate fields which are later used by other parts of the program.

This would be especially useful in games, for example, where each sprite could be a separate instance of a struct, and Ketos code could be used to control the movement of each sprite independently.

**Comment by murarth** [comment]
The static method [`Value::new_foreign_fn`](https://docs.rs/ketos/0.3.1/ketos/value/enum.Value.html#method.new_foreign_fn) can be used to construct a callable `Value` from a Rust closure.

You may also implement the [`ForeignValue`](https://docs.rs/ketos/0.3.1/ketos/value/trait.ForeignValue.html) trait for a Rust struct that you want to insert into a Ketos `Value` (which may be callable or not). This is how `new_foreign_fn` is implemented.

**Comment by vktec** [comment]
@murarth oh, thanks! I thought I might've missed something.

On another note, some more examples might be useful (demonstrating this, for example) since I find them to be a very good reference.
