### ISSUE TITLE
Multithreading support?

### ISSUE THREAD

**Issue by matthiasbeyer** [murarth/ketos#25]
Hi.

Does ketos support multithreading? Can I start a thread within ketos and return something from it? Futures? Mutexes?

Would be nice to have these!

**Comment by hauleth** [comment]
IIRC there is no threading in stdlib and personally I think that there shouldn't be one. Instead make your own interface (could be as a library). Ketos as a language should be kept as small as possible.

**Comment by matthiasbeyer** [comment]
[There is thread stuff in the stdlib](https://doc.rust-lang.org/std/thread/struct.Thread.html) of course!

**Comment by hauleth** [comment]
@matthiasbeyer I meant Ketos stdlib, not Rust one.

**Comment by matthiasbeyer** [comment]
ah, okay, sorry.

Okay then. Keeping the stdlib simple seems like a good idea to me! I will close this now.

Thanks for Ketos, awesome project! I guess I will learn a lot digging through the source!

**Comment by murarth** [comment]
@hauleth is correct. Threading is not currently supported by the interpreter.

It's something I'm interested in exploring, but I don't want to make any half-hearted attempts just to be able to say that it's there.
