### ISSUE TITLE
Derive FromValue and FromValueRef

### ISSUE THREAD

**Issue by MarkMcCaskey** [murarth/ketos#26]
It would be nice to be able to derive these, like Serde's Serialize and Deserialize traits.  I can look into doing this, if this sounds like a good idea to you.

**Comment by murarth** [comment]
Oh, yes. This would be a good idea. I had always intended to do this, but it's slipped my mind since procedural macros were stabilized. I'll start work on this shortly. It shouldn't take long.

**Comment by murarth** [comment]
Ta-da. Just created the `ketos_derive` crate (and published a new version of `ketos` that uses it for tests). The [crate doc](https://docs.rs/ketos_derive/) has the list of derives supported.
