### ISSUE TITLE
Trouble deriving attributes for structs with particular fields

### ISSUE THREAD

**Issue by Wulfsta** [murarth/ketos#29]
I'm having a problem when trying to define a structure that creates a data structure such as a tree or list:

```
...
#[derive(Clone, Debug, ForeignValue, FromValueClone, StructValue)]
pub struct LList {
    data: String,
    point: Option<Box<LList>>,
}
...
```

This causes the complier to throw errors related to `point`. I tried creating wrapper structures for Option and Box and deriving the attributes on those, but that failed. 

I hope I'm not missing something simple, I'm still a bit new to Rust.

**Comment by murarth** [comment]
First, I'm assuming your code is just for playing around. A linked list is generally not the most suitable data structure. Even less so if you're converting to Ketos.

Anyway, you can't derive Ketos traits for a struct containing `Option<_>` because those traits are not implemented for/on `Option<_>`. You can manually implement the traits for a struct that wraps `Option<Box<_>>` instead.

**Comment by Wulfsta** [comment]
Yup! I was playing around to see if I could build a tree in Rust by calling functions in Ketos. 

So I should do something like: 

```
...
struct OptionWrapper<'a, T: 'a + Sized + Clone + Debug>(Option<&'a T>);

struct BoxWrapper<'a, T: 'a + Sized + Clone + Debug>(Box<&'a T>);

#[derive(Clone, Debug, ForeignValue, FromValueClone, StructValue)]
struct LList {
    data: String,
    point: OptionWrapper<BoxWrapper<LList>>
}
...
```

And then implement the necessary Ketos traits on OptionWrapper and BoxWrapper? Will this work if I use `_` rather than specifying those types and lifetimes? I was considering implementing `Deref` to return `self.0` on both of these.

**Comment by murarth** [comment]
>And then implement the necessary Ketos traits on OptionBoxWrapper?

Yes.

>Will this work if I use `_` rather than specifying those traits on the type?

I'm not sure what you mean by this.

**Comment by Wulfsta** [comment]
I wasn't sure if I could just write `struct OptionBoxWrapper(Option<Box<_>>);` but found out pretty quickly that it wasn't allowed. 

Anyhow, I got it to work with a bit of tinkering:

```
extern crate ketos;
#[macro_use] extern crate ketos_derive;

use ketos::{Interpreter,
            Value,
            FromValue,
            ForeignValue,
            ExecError,
            };
use std::fmt::Debug;
use std::ops::Deref;
use std::rc::Rc;

#[derive(Clone, Debug)]
struct OptionBoxWrapper<T: 'static + Sized + Clone + Debug>(Option<Box<T>>);

impl<T: 'static + Sized + Clone + Debug> OptionBoxWrapper<T> {
    fn wrap(w: Option<Box<T>>) -> OptionBoxWrapper<T> {
        OptionBoxWrapper( w )
    }
}

impl<T: 'static + Sized + Clone + Debug> Deref for OptionBoxWrapper<T> {
    type Target = Option<Box<T>>;

    fn deref(&self) -> &Option<Box<T>> {
        &self.0
    }
}

impl<T: 'static + Sized + Clone + Debug> From<OptionBoxWrapper<T>> for Value {
    fn from(v: OptionBoxWrapper<T>) -> Self {
        Value::new_foreign(v)
    }
}

impl<T: 'static + Sized + Clone + Debug> ForeignValue for OptionBoxWrapper<T> {
    fn type_name(&self) -> &'static str { "OptionBoxWrapper" }
}

impl<T: 'static + Sized + Clone + Debug> FromValue for OptionBoxWrapper<T> {
    fn from_value(v: Value) -> Result<Self, ExecError> {
        match v {
            Value::Foreign(fv) => {
                match ForeignValue::downcast_rc(fv) {
                    Ok(v) => {
                        match Rc::try_unwrap(v) {
                            Ok(v) => Ok(v),
                            Err(rc) => Ok((*rc).clone())
                        }
                    }
                    Err(rc) => {
                        Err(
                            ExecError::expected("OptionBoxWrapper",
                                &Value::Foreign(rc)))
                    }
                }
            }
            ref v => Err(
                ExecError::expected("OptionBoxWrapper", v))
        }
    }
}

#[derive(Clone, Debug, ForeignValue, FromValueClone, StructValue)]
struct LList {
    data: String,
    point: OptionBoxWrapper<LList>
}

fn main() {
    let interp = Interpreter::new();
    interp.scope().register_struct_value::<LList>();
    let test = LList { data: "hello".to_string(), point: OptionBoxWrapper::<LList>::wrap(None) };
    println!("Done!")
}
```

I do have a few questions. Is there any way to reduce the repeated `<T: 'static + ... >`? I tried to use `type = ...` but got errors related to using it for traits as well as including the `'static` lifetime. Why does type `T` in this code seem to require a static lifetime? Thanks for the help.

**Comment by murarth** [comment]
Unfortunately, the type bounds on `T` have to be explicit.

The `'static` bound is required because the `ForeignValue` trait requires the standard [`Any`](https://doc.rust-lang.org/std/any/trait.Any.html) trait, which itself requires the `'static` bound. So, in order for your wrapper type to be `'static`, any contained type must also be `'static`.
