### ISSUE TITLE
Consider implementing a DSL macro for constructing `Value`s

### ISSUE THREAD

**Issue by Javyre** [murarth/ketos#33]
The only current way to construct a `Value` easily is by passing it through the interpreter via [`parse_single_expr`](https://docs.rs/ketos/0.10.0/ketos/interpreter/struct.Interpreter.html#method.parse_single_expr)

I suggest making a macro to emulate lisp-like syntax in rust to construct `Value`s
Something similar to [`serde_json`s DSL macro](https://docs.serde.rs/serde_json/#constructing-json-values). : 
```rust
// The type of `john` is `serde_json::Value`. This is computed at compile-time
let john: Value = json!({
  "name": "John Doe",
  "age": 43,
  "phones": [
    "+44 1234567",
    "+44 2345678"
  ]
});
```
Note that serde_json also has the equivalent of `parse_single_expr`: [example from here](https://docs.serde.rs/serde_json/#operating-on-untyped-json-values)
```rust
// Some JSON input data as a &str. Maybe this comes from the user.
let data = r#"{
                "name": "John Doe",
                "age": 43,
                "phones": [
                  "+44 1234567",
                  "+44 2345678"
                ]
              }"#;

// Parse the string of data into serde_json::Value.
let john: Value = serde_json::from_str(data)?;
```
But both functionalities are still useful and relevant.

**Comment by murarth** [comment]
This seems like a good idea, in theory, but I don't think it lends itself to Lisp syntax as well it does to JSON syntax.

The body of the macro wouldn't truly allow Lisp syntax. Expressions would still need to be separated by commas; `foo-bar` would not be seen by Rust's parser as an identifier, but as an expression with a binary operator; Ratio values `1/2`, similar issue.

However, it's not quite true that using the parser is the easiest way to create a Ketos value. `Value` implements `From<T>` for a number of types, including tuples up to 12 elements:

```rust
// Using `.into()`
let value: Value = (true, false, 0, 1, "foo", (3.0, vec![1, 2, 3])).into();
// Or `from()`
let value = Value::from((true, false, 0, 1, "foo", (3.0, vec![1, 2, 3])));
```

Is this sufficient for your use case?

**Comment by Javyre** [comment]
I understand the limitations of rust for this. (I've now some more experience with syn/quote and macro stuff)
Although I love this project, I am now working on bringing the guile library to rust and am no longer using ketos (for now)

sorry for late reponse, I wish you luck with your project!
