### ISSUE TITLE
[documentation] performance

### ISSUE THREAD

**Issue by trsh** [murarth/ketos#37]
Can we please have some mini benchmark, where the speed of running a script is compared with native Rust?

**Comment by murarth** [comment]
I'm not sure what the purpose of this would be. Ketos runs on a bytecode interpreter. Its performance is never going to compare favorably to native compiled Rust code.

A comparison to other scripting languages, such as Python and Lua, would be more apt. In that case, I'm sure Ketos would fare quite poorly, as I have not made any significant effort to profile or improve the interpreter's performance.

**Comment by trsh** [comment]
OK
