### ISSUE TITLE
Warnings from static analysis with clippy

### ISSUE THREAD

**Issue by alienscience** [murarth/ketos#38]
Hello,
  I have been reading through the Ketos code which has been a great learning experience -- thanks.

I noticed that the Rust static analyser called "clippy" is now available on Rust stable:
```
rustup component add clippy-preview
```
More information on installing [is given in the github repository](https://github.com/rust-lang-nursery/rust-clippy).

I ran clippy on the Ketos code and it made lots of suggestions that I would mostly consider to be useful. I have attached the report [clippy.log](https://github.com/murarth/ketos/files/2386424/clippy.log)

Would you be open to people making PRs to make the changes suggested by clippy? Or do you think that the changes suggested  by clippy are not helpful?

**Comment by murarth** [comment]
I looked over the clippy warnings and fixed a few non-trivial issues myself.

I would be happy to accept a PR that addresses the remaining warnings.

**Comment by Robogoogol** [comment]
I think that #46 may fix this.

**Comment by ysimonson** [comment]
Almost all of these are addressed at this point; there's just a couple of linters that are ignored, and one that doesn't have a fix because of borrow checker constraints.
