### ISSUE TITLE
About sexp by sexp multi line editing

### ISSUE THREAD

**Issue by xieyuheng** [murarth/ketos#39]
I saw ketos' repl handles sexp across multi lines in the following way ::
```
ketos=> (+ 1 2
ketos(> 3
ketos(> (+ 4 5
ketos(> )
ketos(> )
15
ketos=>
```

Is it possible to use linefeed to support sexp by sexp multi line editing ?
(like the repl of chez-scheme)

(see also https://github.com/kkawakam/rustyline/issues/153)

**Comment by murarth** [comment]
I want to make sure I'm understanding correctly. What I think you're proposing is this:

* When the user presses Enter, the current input buffer is checked for completeness.
  * If the input represents a complete expression, it is accepted as normal.
  * If the input is incomplete (e.g. unterminated string or unmatched parenthesis), a newline is inserted into the buffer and the user may continue editing.

Is this accurate?

**Comment by xieyuheng** [comment]
yes! for lisp sexp and string literal only.

**Comment by xieyuheng** [comment]
Maybe readline-like crate (like linefeed) is appropriate for this feature,
and we need a crate like `read-sexp` for this ?

**Comment by xieyuheng** [comment]
I have a little repl now :: https://github.com/xieyuheng/jojo/blob/master/src/repl.rs
enjoy using `linefeed` :)

It would be great if `linefeed` can support the `read-sexp` feature,
but we can live without it :P

feel free to close this issue anytime.

**Comment by murarth** [comment]
It would be outside the scope of `linefeed` to support this, but `ketos` could support this by overriding the command that executes when the user presses Enter.

I'll see what I can do.

**Comment by xieyuheng** [comment]
GREAT!

I wish I could learn from you about how to achieve this !

**Comment by murarth** [comment]
I've just pushed a commit that implements this feature.

Let me know if it works as expected or if you find any bugs.

**Comment by xieyuheng** [comment]
Thanks for doing this.
It helped alot.
I am closing this for now ~
