### ISSUE TITLE
Add some kind of meta-module loader

### ISSUE THREAD

**Issue by hauleth** [murarth/ketos#4]
Currently it is kind of troublesome to register new module loader on top of existing ones. It could be useful to have some kind of "meta-module loader" that would allow us to have chain of module loaders.

**Comment by murarth** [comment]
I almost implemented something like this before release. I don't remember what stopped me. Maybe it was something about the meta-loader telling the difference between "found the module and it failed to load" or "didn't find any module by that name." But there is a specific error enum variant for the latter case, so this is possible. I'll see about implementing this very shortly.

**Comment by murarth** [comment]
I've pushed the implementation for this in the latest commit. Thanks for the issue.
