### ISSUE TITLE
Update to Rust 2018

### ISSUE THREAD

**Issue by Robogoogol** [murarth/ketos#44]
Rust 2018 has some [new features and conveniences](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#whats-in-1.31.0-stable). I have tested `cargo fix --edition` and there are no errors.
After that, it would be fixing `extern crate`s, `#[macro_use]`s, etc.

**Comment by murarth** [comment]
Closed by #55
