### ISSUE TITLE
How to access ketos struct members?

### ISSUE THREAD

**Issue by Robogoogol** [murarth/ketos#45]
Suppose I have `(struct Foo ((a integer) (b integer)))`.
How would I get `a` or `b` and do something like this?
```lisp
(define (bar foo) (
  println (+ foo.a foo.b)))
```

**Comment by murarth** [comment]
The `.` function returns a field from a struct value and the `.=` function returns a new struct value with one or more fields replaced.

```lisp
; Returns the `a` field of foo.
(println (. foo :a))
; Returns a new value with `a` set to 1;
; all other fields are the same as the input struct value.
(println (.= foo :a 1))
```

I'm sorry the documentation isn't better. These functions have only a brief mention in the file `docs/functions.md` in this repository.

**Comment by Robogoogol** [comment]
Thanks!
