### ISSUE TITLE
Forking an interpreter

### ISSUE THREAD

**Issue by ysimonson** [murarth/ketos#54]
Is there a way to "fork" an interpreter? i.e. spawn a new thread and run an interpreter in it with the same context as its parent?

`Context` implements clone, so I was hoping to just clone the context and send it to the other thread, but because `Context`s internally use non-Send types (`Rc`), a cloned copy can't be sent.

**Comment by murarth** [comment]
It's not technically impossible, but as you say, there are a lot of `Rc`-wrapped types within the interpreter. It would be technically possible to clone each of the contained values individually, send them to a new thread and rebuild them into a new `Context` structure, but I have a feeling that would be a big ugly mess of code.

**Comment by ysimonson** [comment]
There's too many `Rc`s lying around, and IIRC some of them are for private fields. Instead, I ended up forking the process using [nix](https://github.com/nix-rust/nix). It seems to work for basic use cases. I haven't tried anything too complicated yet though.
