### ISSUE TITLE
[Suggestion] More module functionality

### ISSUE THREAD

**Issue by Robogoogol** [murarth/ketos#56]
Pretty much just
```lisp
(use module :self)
(module/function "argument")
```

### Examples
```lisp
(use math :self)
(print (math/abs -1))
```
Result: `1`

***

```lisp
; foo.ket
(export (bar baz))

(define (bar a) (print (concat a "bar")))
(define (baz b) (print (concat "baz" b)))

; main.ket
(use foo :self)

(foo/bar "foo")
```
Result: `foobar`

I understand that in the previous examples they could have instead been `(use module function)`, `(use math abs)`, and `(use foo bar)`, but this syntax is convenient when you don't want conflicting function/struct names or you want to be more specific and organized with them.

Basically, I think adding functionality like this would make Ketos a more powerful language.

**Comment by murarth** [comment]
I had considered implementing this feature before, but just never decided on the particulars of import syntax and function naming. I like the idea of using `/` as a separator between module and function name.

I'll try to get started working on this soon and we'll see if I run into any issues in the implementation.

**Comment by murarth** [comment]
I've just pushed the implementation of this feature. Let me know if it works as expected.

And thanks for the suggestion!

**Comment by Robogoogol** [comment]
Yes, it works just as expected, thanks!
