### ISSUE TITLE
if operator is broken

### ISSUE THREAD

**Issue by vks** [murarth/ketos#7]
```lisp
ketos=> (if true "then" "else")
"then"
ketos=> (= 0 0)
true
ketos=> (if (= 0 0) "then" "else")
"else"
```

(Commit 2466634096b80331181414b245cf7dd94b8dcdab.)

**Comment by murarth** [comment]
Ha. Well, that's embarassing, isn't it? It's fixed now. It was being compiled to the correct instruction, but the interpreter executed the instruction incorrectly.

**Comment by vks** [comment]
Thanks! Now my extensible FizzBuzz works:

```lisp
(define (map fn li) (map-into fn li ()))

(define (map-into fn li out)
  (if (null li)
    out
    (map-into fn (tail li) (append out (fn (first li))))))

(define (is-divisible a b) (= (rem a b) 0))

(define tags '((3 "Fizz") (5 "Buzz")))

(define (evaluate i)
  (let ((find-desc (lambda (tag)
          (if (is-divisible i (first tag)) (last tag) "")))
        (desc (format "~{~a~}" (map find-desc tags))))
    (if (= desc "") (format "~a" i) desc)))

(define (fizzbuzz start end)
  (if (<= start end) (do
    (println "~a" (evaluate start))
    (fizzbuzz (+ 1 start) end))))

(fizzbuzz 1 100)
```

Unfortunately it is not as concise as the [inspiring Haskell implementation](https://wiki.haskell.org/Haskell_Quiz/FizzBuzz/Solution_Acontorer).

Is it possible to import the standard library when running scripts?

**Comment by murarth** [comment]
>Is it possible to import the standard library when running scripts?

Good news! I've just pushed a commit that causes the interpreter to search a list of paths in the environment variable, `KETOS_PATH`. That should make using the standard library a bit easier.
